### ISSUE TITLE
RFC: Exploring and sharing spatial proteomics data

### ISSUE THREAD

**Issue by lgatto** [lgatto/lgatto.github.io#8]
Dear @Kohze and @rollerlibrarian

*Introductions:* @Kohze is currently working on the project described in the post and @rollerlibrarian is involved with me in the Open Research Project project.

I have just added a draft post [*Exploring and sharing spatial proteomics data*](https://github.com/lgatto/lgatto.github.io/blob/master/_drafts/2017-05-07-spatialmap-proposal.md). Feel free to comment and make suggestions in this issue.

**Comment by Kohze** [comment]
@lgatto 
Thats an interesting draft. As you state in the introduction, its probably difficult to get funding for a platform itself. In contrast if the grand application was about the development of analysis tools that are only now applicable after having the platform (transfer learning between datasets) I see higher chances as we would promise a immediate improvement of proteomic data analysis capabilities.

**Comment by lgatto** [comment]
Analyses across datasets don't need the platform, they need access to multiple datasets, which is already the case. Such analyses require skills and development that are often different from the development of a platform. Either it is a **big** grant and it is possible to get dedicated staff to work on both aspects, or a compromise ends up prioritising the data analysis aspects (because these are the ones that can be more easily labelled as novel and that are going to generate new biological knowledge) rather than the interface/resource, that becomes secondary in the project and funding allocation.

**Comment by Kohze** [comment]
That's the point of the argumentation. To take something the team is already strong in to create a minimum of extra cost and at the same time allocate the necessary funding into SpatialMap which would otherwise likely not receive funding.  By creating an argumentation towards the necessity of the platform to collect more datasets than are currently openly available (to get potentially hundreds) would imply for the fund itself that the fund could be re-allocated there without conflicts of interest.
